import static org.junit.Assert.assertEquals;

import org.junit.Test;

public class TestVigenereCipher {

	/**
	 * Test Case Number 1
	 */
	@Test
	public void testCase1() {
		VigenereCipherBreaker vcb = new VigenereCipherBreaker();
		vcb.setCipherText("OICPWZXZEVLGCLNFSYPGALPXWZJTEGALPCSIIWDHOIECCBFWPAHOPCGALPCCBROASNWTYHOID"
				+ "BIHVPSCSIDEVLSYPGDLZDSLXSTBNWOTTMICPBAPJEVLCLCSUSEQCUHZQFBPPDOUHESSFLLGSUSCPGWINET"
				+ "VVESSZXLEIZUFZMVYNLBXYZESALPXRPWLRFLIHTHOXSPANPZCWMCZCJPPTQMALPXOISFEHOIZYZFXSTBNCZ"
				+ "FQHRYZHKSTDWNRZCSALPXPLGLFGLXSPMJLLYULXSTBNWESSFTFDVALPSITEYCOJIQZFDECOOUHHSWSIDZAL"
				+ "QLJGLIESSTEDEVLGCLNFSYPGDIDPSNIYTIZFPNOBWPEVLTPZDSIHSCHVPNFHDJPBVYRSHVXSTBRXSPMJEYN"
				+ "VHRRPHOIHZFSHLCSALPZBLWHSCKS");
		assertEquals(5, vcb.computeKeyLength());
	}

	/**
	 * Test Case Number 2
	 */
	@Test
	public void testCase2() {
		VigenereCipherBreaker vcb = new VigenereCipherBreaker();
		vcb.setCipherText("VVVXSQWPSNJMUMJOKKLGFQAVEXAHWRVTMFXVVRKAJTVMFLOPHYWJDSTXKAGFVVTPHKYEPP"
				+ "JOKPSWACJVSIGGVOLXLVMQPVCMGOGMFLAKENVRMIUAKTKVHIXCFJZRAHWFHLIUMHCIRFWGFOETIUNE"
				+ "QVJWEHOSJWVQFYWKYMPGQHWISOPKHYFYV");
		assertEquals(7, vcb.computeKeyLength());
	}

	/**
	 * Test Case Number 3
	 */
	@Test
	public void testCase3() {
		VigenereCipherBreaker vcb = new VigenereCipherBreaker();
		vcb.setCipherText("ATVDVKGSTBPRPOWLJYRGJXDJPWSDUBZQKNEUWLJTPBBOEQUWLWUBOQIOVTYINTZIWNSXKPWNTZ"
				+ "QMOYPWUFQUVLJXDCGFSRKZMEORZRDVYUMGXEAOFWLJTFWDRAWGWSUAAQCLADMLRYUAPNCKZCQHNZPACREN"
				+ "QVXUGPVOELUJLRLEVCFSLMGYIWNHDNDOEQDRIZOICIOVJDZJKCMANOOGEYYCOICSSZQXVXOZGXERTYKIYN"
				+ "LZRDITWSMSZOMBUYPTKIWKPVHYUSJDRIYHVMYNFFDCNZDQUVFBNOJWUTBQOSLADRINPBHYUJPWLJNLIMBE"
				+ "BNKEWJHVMDHBVWMRKFWDGIMNQSYNHDNDOQWWMYHHKTSNUJHWPEHOJSN");
		assertEquals(11, vcb.computeKeyLength());

	}
}
